collections:
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: /nooblist
url: https://orllck.github.io/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
